# Numpy Implementation

In [1]:
import numpy as np
# Create a 2D Numpy array of size 1x3 with elements of your choice
arr1 = np.array([[10, 20, 30]])

# Create a Numpy array of length 50 with zeroes as its elements
arr2 = np.zeros(50, dtype = int)

#Create a Numpy array of length 3x2 with elements of your choice
arr3 = np.array([[1, 2], [3, 4], [5, 6]])

arr4 = np.dot(arr1, arr3)

#Change 5th element of arr2 to a different number
arr2[4] = 10

if np.shape(arr4) == (1,2) and arr2[4] != 0:
  print("Passed")
else:
  print("Fail")

Passed


In [2]:
import numpy as np

#Task: Perform the dot product of I and 9I+1 using numpy, here I is referred to as an 3x3 Identity matrix.
Imatrix = np.identity(3, dtype = int)
_Imatrix = (9 * Imatrix) + 1

productMatrix = np.dot(Imatrix, _Imatrix)
print(productMatrix)

[[10  1  1]
 [ 1 10  1]
 [ 1  1 10]]


# Pandas Implementation

In [3]:
import pandas as pd

## Create a DataFrame from a dictionary
data = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, 30, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}

df = pd.DataFrame(data)

#Display the first 2 rows of the data frame
print(df.head(2))

#Print the age column
print(df['Age'])

#Filter rows where age is greater than 26
filter_age = df[df['Age'] > 26]
print(filter_age)

#Add a new column 'Country' with the value 'India' for all rows
df['Country'] = 'India'
print(df)

data1 = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, None, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}

df2= pd.DataFrame(data1)

# Fill missing values in the 'Age' column with the mean age
meanAge = df2['Age'].mean()
df2['Age'].fillna(meanAge, inplace = True)
print(df2)

     Name  Age       City
0  Ramesh   25  Bangalore
1  Mahesh   30     Mumbai
0    25
1    30
2    35
Name: Age, dtype: int64
     Name  Age    City
1  Mahesh   30  Mumbai
2  Suresh   35   Delhi
     Name  Age       City Country
0  Ramesh   25  Bangalore   India
1  Mahesh   30     Mumbai   India
2  Suresh   35      Delhi   India
     Name   Age       City
0  Ramesh  25.0  Bangalore
1  Mahesh  30.0     Mumbai
2  Suresh  35.0      Delhi


# Matplotlib Implementation

In [5]:
import matplotlib.pyplot as plt
import numpy as np #numpy module.



xpoints = np.array([1,2,3,4])
ypoints = np.array([2,4,6,8])

#Plot these points without drawing a line
plt.figure(figsize = (2, 2))
plt.scatter(xpoints, ypoints, color = 'black')
plt.show()

#Plotting with marker: Plot these points with a marker(Star marker)
plt.figure(figsize = (2, 2))
plt.scatter(xpoints, ypoints, marker = '*', color = 'black')
plt.show()

#Using fmt format, add circular marker,red color and Dashed line
#Add xlabel,ylabel and title for the plot.
plt.figure(figsize = (2, 2))
plt.plot(xpoints, ypoints, 'ro--')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('plot of points')
plt.show()

#Create a scatter plot for xpoints and ypoints
#Set color to the scatter plot. Blue,Green,Red and yellow color for each point respectively
plt.figure(figsize = (2, 2))
plt.scatter(xpoints, ypoints, c = ['blue', 'green', 'red', 'yellow'])
plt.title('Scatter Plot Colors')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

# Miscellaneous Modules Implementation

In [ ]:
import random
import numpy as np

#Set the seed of random to 20
np.random.seed(20)

arr1 = np.array([1,24,31,45,73,81,94,25])

#Using the random module pick 4 different random numbers from arr1 and return their sum.
randomNumbers = random.sample(list(arr1), 4) # converting numpy array into list
sumOfRandomNumbers = sum(randomNumbers)

print("Random numbers :", randomNumbers)
print("Sum of random numbers:", sumOfRandomNumbers)

Random numbers : [73, 24, 94, 81]
Sum of random numbers: 272
